name: check-version
run-name: Check Version
on:
  pull_request:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - id: check # This will be the reference for getting the outputs.
        uses: EndBug/version-check@v2 # You can choose the version/branch you prefer.
      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: |
          echo "No version change :/"'
          exit: 1